import Navbar from '@/components/sections/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/sections/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by Moaz007Malik',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
      <main>
      </main>
        {children}<Footer/>
        </body>
    </html>
  )
}
